name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build, Convert and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Build Docker image"
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: resume-builder:latest

      - name: "Generate PDF"
        uses: addnab/docker-run-action@v3
        with:
          image: resume-builder:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            mkdir -p out
            pdflatex -output-directory=out resume.tex

      - name: "Convert to PNG and WebP"
        uses: addnab/docker-run-action@v3
        with:
          image: resume-builder:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            sh <<EOF
              cd /data
              pdftoppm -png out/resume.pdf > out/resume.png
              convert out/resume.png -resize 700x906 out/resume.resized.webp && \
              convert out/resume.png -resize 906x700 out/resume.resized.png
            EOF

      - name: "Commit changes and push"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply pdflatex changes

      - name: "R2 Upload Action"
        uses: ryand56/r2-upload-action@v1.4
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: out
          destination-dir: ./resume/
